### ISSUE TITLE
Sarvesh  - Mini/Major and Robotics Projects Development

### ISSUE THREAD

**Issue by computronicslab** [computronicslab/Business-Development#15]
For Sarvesh : 15 mini projects for school - 5 Pcs each
10 mini projects for college based on IC’s - 3 Pcs each
5 types of Robots - 3 Pcs each
10 simple projects on 8051 - 2 Pcs each
10 simple projects on AVR - 2 Pcs each
15 mini projects on Arduino and simple sensors - 3 Pcs each
5 Robots in Arduino - 2 Pcs each
20 Major projects (general type ) - 1 Pcs each
10 types of products prototypes - 2 Pcs each
Development boards - All types
5 types of electronics kits
20 Pcs HAP
10 Pcs - college Exhibition Level Projects.

**Comment by computronicslab** [comment]
Wireless Power Transmission - 5 PCS
Fire Alarm using IC 555 - 5 PCS
Cell Phone Detector - 3 PCS
Smoke Alarm - 3 Pcs
Arduino based Home Automation using Bluetooth
Different Types of Robots

**Comment by AAKASHNCCE** [comment]
he will come after 12.... then i will assign him these task.
