### ISSUE TITLE
Online Sale on Computronics Lab Website

### ISSUE THREAD

**Issue by computronicslab** [computronicslab/Business-Development#21]

**Comment by AAKASHNCCE** [comment]
our website will work as a shown case and we can also design better ......... but for online sale its not a good platform.

**Comment by computronicslab** [comment]
Please check how to add payment gateway. Also redesign our website for online sale , through any other company or individual.

**Comment by computronicslab** [comment]
Contact Ankit xantatech - +91 98716 11299
